"""Initial migration.

Revision ID: f175b179cf7e
Revises: 
Create Date: 2025-03-10 22:52:28.533487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f175b179cf7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boek_genre_association')
    op.drop_table('boek_auteur_association')
    op.drop_table('genre')
    op.drop_table('thema')
    op.drop_table('boek')
    op.drop_table('Gebruiker')
    op.drop_table('auteur')
    op.drop_table('boek_thema_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boek_thema_association',
    sa.Column('boek_id', sa.INTEGER(), nullable=True),
    sa.Column('thema_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['boek_id'], ['boek.ISBN'], ),
    sa.ForeignKeyConstraint(['thema_id'], ['thema.id'], )
    )
    op.create_table('auteur',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('naam', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Gebruiker',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('naam', sa.VARCHAR(), nullable=True),
    sa.Column('achternaam', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('paswoord', sa.VARCHAR(), nullable=True),
    sa.Column('geboortedtm', sa.VARCHAR(), nullable=True),
    sa.Column('tel_nr', sa.INTEGER(), nullable=True),
    sa.Column('rol', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boek',
    sa.Column('ISBN', sa.VARCHAR(), nullable=False),
    sa.Column('titel', sa.VARCHAR(), nullable=False),
    sa.Column('gereserveerd', sa.BOOLEAN(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('beschrijving', sa.VARCHAR(), nullable=False),
    sa.Column('bvdm', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('ISBN')
    )
    op.create_table('thema',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('naam', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genre',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('naam', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boek_auteur_association',
    sa.Column('boek_id', sa.INTEGER(), nullable=True),
    sa.Column('auteur_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['auteur_id'], ['auteur.id'], ),
    sa.ForeignKeyConstraint(['boek_id'], ['boek.ISBN'], )
    )
    op.create_table('boek_genre_association',
    sa.Column('boek_id', sa.INTEGER(), nullable=True),
    sa.Column('genre_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['boek_id'], ['boek.ISBN'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], )
    )
    # ### end Alembic commands ###
